version: '3.8'

services:
  vllm:
    build:
      context: .
      dockerfile: Dockerfile.vllm
    container_name: vllm-qwen3
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - MASTER_ADDR=localhost
      - MASTER_PORT=29501
      - NCCL_DEBUG=INFO
      - NCCL_SOCKET_IFNAME=eth0
      - NCCL_IB_DISABLE=1
      - NCCL_P2P_DISABLE=1
    volumes:
      - ./kyrie12infer/qwen3_0.6b:/app/kyrie12infer/qwen3_0.6b:ro
      - ./logs:/app/logs
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true
    shm_size: '2gb'